/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.Adeptness.ui.internal.AdeptnessActivator;

public class AdeptnessUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AdeptnessActivator.getInstance().getInjector("org.xtext.example.mydsl.Adeptness");
	}

}
