/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.adeptness;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.adeptness.AdeptnessPackage
 * @generated
 */
public interface AdeptnessFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AdeptnessFactory eINSTANCE = org.xtext.example.mydsl.adeptness.impl.AdeptnessFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Adeptness</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Adeptness</em>'.
   * @generated
   */
  Adeptness createAdeptness();

  /**
   * Returns a new object of class '<em>Abstract Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Element</em>'.
   * @generated
   */
  AbstractElement createAbstractElement();

  /**
   * Returns a new object of class '<em>Imports</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imports</em>'.
   * @generated
   */
  Imports createImports();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Validation Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Validation Plan</em>'.
   * @generated
   */
  ValidationPlan createValidationPlan();

  /**
   * Returns a new object of class '<em>Test</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Test</em>'.
   * @generated
   */
  Test createTest();

  /**
   * Returns a new object of class '<em>Testing Oracle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Testing Oracle</em>'.
   * @generated
   */
  TestingOracle createTestingOracle();

  /**
   * Returns a new object of class '<em>Parameters</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameters</em>'.
   * @generated
   */
  Parameters createParameters();

  /**
   * Returns a new object of class '<em>Inputs</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inputs</em>'.
   * @generated
   */
  Inputs createInputs();

  /**
   * Returns a new object of class '<em>Monitoring File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Monitoring File</em>'.
   * @generated
   */
  MonitoringFile createMonitoringFile();

  /**
   * Returns a new object of class '<em>Monitoring Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Monitoring Plan</em>'.
   * @generated
   */
  MonitoringPlan createMonitoringPlan();

  /**
   * Returns a new object of class '<em>Monitoring Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Monitoring Variable</em>'.
   * @generated
   */
  MonitoringVariable createMonitoringVariable();

  /**
   * Returns a new object of class '<em>Sig type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sig type</em>'.
   * @generated
   */
  Sig_type createSig_type();

  /**
   * Returns a new object of class '<em>Signal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Signal</em>'.
   * @generated
   */
  Signal createSignal();

  /**
   * Returns a new object of class '<em>Import Monitoring Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import Monitoring Plan</em>'.
   * @generated
   */
  ImportMonitoringPlan createImportMonitoringPlan();

  /**
   * Returns a new object of class '<em>Oracle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Oracle</em>'.
   * @generated
   */
  Oracle createOracle();

  /**
   * Returns a new object of class '<em>While</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>While</em>'.
   * @generated
   */
  While createWhile();

  /**
   * Returns a new object of class '<em>When</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>When</em>'.
   * @generated
   */
  When createWhen();

  /**
   * Returns a new object of class '<em>After When</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>After When</em>'.
   * @generated
   */
  AfterWhen createAfterWhen();

  /**
   * Returns a new object of class '<em>Wait</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Wait</em>'.
   * @generated
   */
  Wait createWait();

  /**
   * Returns a new object of class '<em>During</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>During</em>'.
   * @generated
   */
  During createDuring();

  /**
   * Returns a new object of class '<em>Checks</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Checks</em>'.
   * @generated
   */
  Checks createChecks();

  /**
   * Returns a new object of class '<em>Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Description</em>'.
   * @generated
   */
  Description createDescription();

  /**
   * Returns a new object of class '<em>Fail Reason</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fail Reason</em>'.
   * @generated
   */
  FailReason createFailReason();

  /**
   * Returns a new object of class '<em>Reason</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reason</em>'.
   * @generated
   */
  Reason createReason();

  /**
   * Returns a new object of class '<em>XPeaks</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XPeaks</em>'.
   * @generated
   */
  XPeaks createXPeaks();

  /**
   * Returns a new object of class '<em>Const Deg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Const Deg</em>'.
   * @generated
   */
  ConstDeg createConstDeg();

  /**
   * Returns a new object of class '<em>High Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>High Time</em>'.
   * @generated
   */
  HighTime createHighTime();

  /**
   * Returns a new object of class '<em>High Peak</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>High Peak</em>'.
   * @generated
   */
  HighPeak createHighPeak();

  /**
   * Returns a new object of class '<em>Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reference</em>'.
   * @generated
   */
  Reference createReference();

  /**
   * Returns a new object of class '<em>Precond Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Precond Reference</em>'.
   * @generated
   */
  PrecondReference createPrecondReference();

  /**
   * Returns a new object of class '<em>Same</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Same</em>'.
   * @generated
   */
  Same createSame();

  /**
   * Returns a new object of class '<em>Not Same</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Not Same</em>'.
   * @generated
   */
  NotSame createNotSame();

  /**
   * Returns a new object of class '<em>Upper</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Upper</em>'.
   * @generated
   */
  Upper createUpper();

  /**
   * Returns a new object of class '<em>Lower</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lower</em>'.
   * @generated
   */
  Lower createLower();

  /**
   * Returns a new object of class '<em>Range</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Range</em>'.
   * @generated
   */
  Range createRange();

  /**
   * Returns a new object of class '<em>Gap</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gap</em>'.
   * @generated
   */
  Gap createGap();

  /**
   * Returns a new object of class '<em>Inclusive Bound</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inclusive Bound</em>'.
   * @generated
   */
  InclusiveBound createInclusiveBound();

  /**
   * Returns a new object of class '<em>Exactly</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exactly</em>'.
   * @generated
   */
  Exactly createExactly();

  /**
   * Returns a new object of class '<em>At most</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>At most</em>'.
   * @generated
   */
  At_most createAt_most();

  /**
   * Returns a new object of class '<em>At least</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>At least</em>'.
   * @generated
   */
  At_least createAt_least();

  /**
   * Returns a new object of class '<em>Bound up</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bound up</em>'.
   * @generated
   */
  Bound_up createBound_up();

  /**
   * Returns a new object of class '<em>Bound Down</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bound Down</em>'.
   * @generated
   */
  Bound_Down createBound_Down();

  /**
   * Returns a new object of class '<em>BOOLEAN</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BOOLEAN</em>'.
   * @generated
   */
  BOOLEAN createBOOLEAN();

  /**
   * Returns a new object of class '<em>DOUBLE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DOUBLE</em>'.
   * @generated
   */
  DOUBLE createDOUBLE();

  /**
   * Returns a new object of class '<em>Time Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Time Type</em>'.
   * @generated
   */
  TimeType createTimeType();

  /**
   * Returns a new object of class '<em>Data Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Type</em>'.
   * @generated
   */
  DataType createDataType();

  /**
   * Returns a new object of class '<em>Package Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Package Declaration</em>'.
   * @generated
   */
  PackageDeclaration createPackageDeclaration();

  /**
   * Returns a new object of class '<em>Expressions Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expressions Model</em>'.
   * @generated
   */
  ExpressionsModel createExpressionsModel();

  /**
   * Returns a new object of class '<em>Abstract Element2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Element2</em>'.
   * @generated
   */
  AbstractElement2 createAbstractElement2();

  /**
   * Returns a new object of class '<em>Operators</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operators</em>'.
   * @generated
   */
  Operators createOperators();

  /**
   * Returns a new object of class '<em>Comp Op</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comp Op</em>'.
   * @generated
   */
  CompOp createCompOp();

  /**
   * Returns a new object of class '<em>Logic Op</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logic Op</em>'.
   * @generated
   */
  LogicOp createLogicOp();

  /**
   * Returns a new object of class '<em>Op</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op</em>'.
   * @generated
   */
  Op createOp();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AdeptnessPackage getAdeptnessPackage();

} //AdeptnessFactory
