/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.adeptness;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.adeptness.AdeptnessFactory
 * @model kind="package"
 * @generated
 */
public interface AdeptnessPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "adeptness";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Adeptness";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "adeptness";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AdeptnessPackage eINSTANCE = org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.AdeptnessImpl <em>Adeptness</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getAdeptness()
   * @generated
   */
  int ADEPTNESS = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADEPTNESS__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Adeptness</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADEPTNESS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.AbstractElementImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.ImportImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.TypeImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getType()
   * @generated
   */
  int TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.SignalImpl <em>Signal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.SignalImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getSignal()
   * @generated
   */
  int SIGNAL = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Oracle</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL__ORACLE = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Signal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.OracleImpl <em>Oracle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.OracleImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getOracle()
   * @generated
   */
  int ORACLE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORACLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Check</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORACLE__CHECK = 1;

  /**
   * The number of structural features of the '<em>Oracle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORACLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.CheckImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getCheck()
   * @generated
   */
  int CHECK = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__NAME = 0;

  /**
   * The feature id for the '<em><b>Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__REFERENCE = 1;

  /**
   * The feature id for the '<em><b>Fail Reason</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__FAIL_REASON = 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__DESCRIPTION = 3;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.FailReasonImpl <em>Fail Reason</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.FailReasonImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getFailReason()
   * @generated
   */
  int FAIL_REASON = 7;

  /**
   * The feature id for the '<em><b>High Peak</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAIL_REASON__HIGH_PEAK = 0;

  /**
   * The feature id for the '<em><b>High Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAIL_REASON__HIGH_TIME = 1;

  /**
   * The feature id for the '<em><b>Const Deg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAIL_REASON__CONST_DEG = 2;

  /**
   * The feature id for the '<em><b>XPeaks</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAIL_REASON__XPEAKS = 3;

  /**
   * The number of structural features of the '<em>Fail Reason</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAIL_REASON_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.XPeaksImpl <em>XPeaks</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.XPeaksImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getXPeaks()
   * @generated
   */
  int XPEAKS = 8;

  /**
   * The feature id for the '<em><b>Cant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPEAKS__CANT = 0;

  /**
   * The feature id for the '<em><b>NPeaks</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPEAKS__NPEAKS = 1;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPEAKS__TIME = 2;

  /**
   * The number of structural features of the '<em>XPeaks</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPEAKS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.ConstDegImpl <em>Const Deg</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.ConstDegImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getConstDeg()
   * @generated
   */
  int CONST_DEG = 9;

  /**
   * The feature id for the '<em><b>Cant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_DEG__CANT = 0;

  /**
   * The number of structural features of the '<em>Const Deg</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_DEG_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.HighTimeImpl <em>High Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.HighTimeImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getHighTime()
   * @generated
   */
  int HIGH_TIME = 10;

  /**
   * The feature id for the '<em><b>Cant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HIGH_TIME__CANT = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HIGH_TIME__TIME = 1;

  /**
   * The number of structural features of the '<em>High Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HIGH_TIME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.HighPeakImpl <em>High Peak</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.HighPeakImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getHighPeak()
   * @generated
   */
  int HIGH_PEAK = 11;

  /**
   * The feature id for the '<em><b>Cant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HIGH_PEAK__CANT = 0;

  /**
   * The number of structural features of the '<em>High Peak</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HIGH_PEAK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.ReferenceImpl <em>Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.ReferenceImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getReference()
   * @generated
   */
  int REFERENCE = 12;

  /**
   * The feature id for the '<em><b>Upper</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__UPPER = 0;

  /**
   * The feature id for the '<em><b>Lower</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__LOWER = 1;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__RANGE = 2;

  /**
   * The feature id for the '<em><b>Gap</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__GAP = 3;

  /**
   * The number of structural features of the '<em>Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.UpperImpl <em>Upper</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.UpperImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getUpper()
   * @generated
   */
  int UPPER = 13;

  /**
   * The feature id for the '<em><b>Bound upp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPPER__BOUND_UPP = 0;

  /**
   * The number of structural features of the '<em>Upper</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPPER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.LowerImpl <em>Lower</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.LowerImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getLower()
   * @generated
   */
  int LOWER = 14;

  /**
   * The feature id for the '<em><b>Bound lower</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOWER__BOUND_LOWER = 0;

  /**
   * The number of structural features of the '<em>Lower</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOWER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.RangeImpl <em>Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.RangeImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getRange()
   * @generated
   */
  int RANGE = 15;

  /**
   * The feature id for the '<em><b>Bound lower</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__BOUND_LOWER = 0;

  /**
   * The feature id for the '<em><b>Bound upp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__BOUND_UPP = 1;

  /**
   * The number of structural features of the '<em>Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.GapImpl <em>Gap</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.GapImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getGap()
   * @generated
   */
  int GAP = 16;

  /**
   * The feature id for the '<em><b>Bound lower</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAP__BOUND_LOWER = 0;

  /**
   * The feature id for the '<em><b>Bound upp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAP__BOUND_UPP = 1;

  /**
   * The number of structural features of the '<em>Gap</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.InclusiveBoundImpl <em>Inclusive Bound</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.InclusiveBoundImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getInclusiveBound()
   * @generated
   */
  int INCLUSIVE_BOUND = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUSIVE_BOUND__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUSIVE_BOUND__VALUE = 1;

  /**
   * The number of structural features of the '<em>Inclusive Bound</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUSIVE_BOUND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.Bound_upImpl <em>Bound up</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.Bound_upImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getBound_up()
   * @generated
   */
  int BOUND_UP = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUND_UP__VALUE = 0;

  /**
   * The number of structural features of the '<em>Bound up</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUND_UP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.Bound_DownImpl <em>Bound Down</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.Bound_DownImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getBound_Down()
   * @generated
   */
  int BOUND_DOWN = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUND_DOWN__VALUE = 0;

  /**
   * The number of structural features of the '<em>Bound Down</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUND_DOWN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.BOOLEANImpl <em>BOOLEAN</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.BOOLEANImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getBOOLEAN()
   * @generated
   */
  int BOOLEAN = 20;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__BOOL = 0;

  /**
   * The number of structural features of the '<em>BOOLEAN</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.DOUBLEImpl <em>DOUBLE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.DOUBLEImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getDOUBLE()
   * @generated
   */
  int DOUBLE = 21;

  /**
   * The feature id for the '<em><b>DVal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE__DVAL = 0;

  /**
   * The number of structural features of the '<em>DOUBLE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.DataTypeImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.adeptness.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.adeptness.impl.PackageDeclarationImpl
   * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getPackageDeclaration()
   * @generated
   */
  int PACKAGE_DECLARATION = 23;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__ELEMENTS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Package Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Adeptness <em>Adeptness</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Adeptness</em>'.
   * @see org.xtext.example.mydsl.adeptness.Adeptness
   * @generated
   */
  EClass getAdeptness();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.adeptness.Adeptness#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.adeptness.Adeptness#getElements()
   * @see #getAdeptness()
   * @generated
   */
  EReference getAdeptness_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.xtext.example.mydsl.adeptness.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.xtext.example.mydsl.adeptness.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.adeptness.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see org.xtext.example.mydsl.adeptness.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.mydsl.adeptness.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.adeptness.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.adeptness.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Signal <em>Signal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Signal</em>'.
   * @see org.xtext.example.mydsl.adeptness.Signal
   * @generated
   */
  EClass getSignal();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.adeptness.Signal#getOracle <em>Oracle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Oracle</em>'.
   * @see org.xtext.example.mydsl.adeptness.Signal#getOracle()
   * @see #getSignal()
   * @generated
   */
  EReference getSignal_Oracle();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Oracle <em>Oracle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Oracle</em>'.
   * @see org.xtext.example.mydsl.adeptness.Oracle
   * @generated
   */
  EClass getOracle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.adeptness.Oracle#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.adeptness.Oracle#getName()
   * @see #getOracle()
   * @generated
   */
  EAttribute getOracle_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.adeptness.Oracle#getCheck <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Check</em>'.
   * @see org.xtext.example.mydsl.adeptness.Oracle#getCheck()
   * @see #getOracle()
   * @generated
   */
  EReference getOracle_Check();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see org.xtext.example.mydsl.adeptness.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.adeptness.Check#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.adeptness.Check#getName()
   * @see #getCheck()
   * @generated
   */
  EAttribute getCheck_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Check#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reference</em>'.
   * @see org.xtext.example.mydsl.adeptness.Check#getReference()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Reference();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.adeptness.Check#getFailReason <em>Fail Reason</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fail Reason</em>'.
   * @see org.xtext.example.mydsl.adeptness.Check#getFailReason()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_FailReason();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.adeptness.Check#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.example.mydsl.adeptness.Check#getDescription()
   * @see #getCheck()
   * @generated
   */
  EAttribute getCheck_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.FailReason <em>Fail Reason</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fail Reason</em>'.
   * @see org.xtext.example.mydsl.adeptness.FailReason
   * @generated
   */
  EClass getFailReason();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.FailReason#getHighPeak <em>High Peak</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>High Peak</em>'.
   * @see org.xtext.example.mydsl.adeptness.FailReason#getHighPeak()
   * @see #getFailReason()
   * @generated
   */
  EReference getFailReason_HighPeak();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.FailReason#getHighTime <em>High Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>High Time</em>'.
   * @see org.xtext.example.mydsl.adeptness.FailReason#getHighTime()
   * @see #getFailReason()
   * @generated
   */
  EReference getFailReason_HighTime();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.FailReason#getConstDeg <em>Const Deg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Const Deg</em>'.
   * @see org.xtext.example.mydsl.adeptness.FailReason#getConstDeg()
   * @see #getFailReason()
   * @generated
   */
  EReference getFailReason_ConstDeg();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.FailReason#getXPeaks <em>XPeaks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>XPeaks</em>'.
   * @see org.xtext.example.mydsl.adeptness.FailReason#getXPeaks()
   * @see #getFailReason()
   * @generated
   */
  EReference getFailReason_XPeaks();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.XPeaks <em>XPeaks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XPeaks</em>'.
   * @see org.xtext.example.mydsl.adeptness.XPeaks
   * @generated
   */
  EClass getXPeaks();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.XPeaks#getCant <em>Cant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cant</em>'.
   * @see org.xtext.example.mydsl.adeptness.XPeaks#getCant()
   * @see #getXPeaks()
   * @generated
   */
  EReference getXPeaks_Cant();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.XPeaks#getNPeaks <em>NPeaks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>NPeaks</em>'.
   * @see org.xtext.example.mydsl.adeptness.XPeaks#getNPeaks()
   * @see #getXPeaks()
   * @generated
   */
  EReference getXPeaks_NPeaks();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.XPeaks#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.example.mydsl.adeptness.XPeaks#getTime()
   * @see #getXPeaks()
   * @generated
   */
  EReference getXPeaks_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.ConstDeg <em>Const Deg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Const Deg</em>'.
   * @see org.xtext.example.mydsl.adeptness.ConstDeg
   * @generated
   */
  EClass getConstDeg();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.ConstDeg#getCant <em>Cant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cant</em>'.
   * @see org.xtext.example.mydsl.adeptness.ConstDeg#getCant()
   * @see #getConstDeg()
   * @generated
   */
  EReference getConstDeg_Cant();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.HighTime <em>High Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>High Time</em>'.
   * @see org.xtext.example.mydsl.adeptness.HighTime
   * @generated
   */
  EClass getHighTime();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.HighTime#getCant <em>Cant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cant</em>'.
   * @see org.xtext.example.mydsl.adeptness.HighTime#getCant()
   * @see #getHighTime()
   * @generated
   */
  EReference getHighTime_Cant();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.HighTime#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.example.mydsl.adeptness.HighTime#getTime()
   * @see #getHighTime()
   * @generated
   */
  EReference getHighTime_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.HighPeak <em>High Peak</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>High Peak</em>'.
   * @see org.xtext.example.mydsl.adeptness.HighPeak
   * @generated
   */
  EClass getHighPeak();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.HighPeak#getCant <em>Cant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cant</em>'.
   * @see org.xtext.example.mydsl.adeptness.HighPeak#getCant()
   * @see #getHighPeak()
   * @generated
   */
  EReference getHighPeak_Cant();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Reference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference</em>'.
   * @see org.xtext.example.mydsl.adeptness.Reference
   * @generated
   */
  EClass getReference();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Reference#getUpper <em>Upper</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Upper</em>'.
   * @see org.xtext.example.mydsl.adeptness.Reference#getUpper()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Upper();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Reference#getLower <em>Lower</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lower</em>'.
   * @see org.xtext.example.mydsl.adeptness.Reference#getLower()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Lower();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Reference#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see org.xtext.example.mydsl.adeptness.Reference#getRange()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Range();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Reference#getGap <em>Gap</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Gap</em>'.
   * @see org.xtext.example.mydsl.adeptness.Reference#getGap()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Gap();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Upper <em>Upper</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Upper</em>'.
   * @see org.xtext.example.mydsl.adeptness.Upper
   * @generated
   */
  EClass getUpper();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Upper#getBound_upp <em>Bound upp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bound upp</em>'.
   * @see org.xtext.example.mydsl.adeptness.Upper#getBound_upp()
   * @see #getUpper()
   * @generated
   */
  EReference getUpper_Bound_upp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Lower <em>Lower</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lower</em>'.
   * @see org.xtext.example.mydsl.adeptness.Lower
   * @generated
   */
  EClass getLower();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Lower#getBound_lower <em>Bound lower</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bound lower</em>'.
   * @see org.xtext.example.mydsl.adeptness.Lower#getBound_lower()
   * @see #getLower()
   * @generated
   */
  EReference getLower_Bound_lower();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range</em>'.
   * @see org.xtext.example.mydsl.adeptness.Range
   * @generated
   */
  EClass getRange();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Range#getBound_lower <em>Bound lower</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bound lower</em>'.
   * @see org.xtext.example.mydsl.adeptness.Range#getBound_lower()
   * @see #getRange()
   * @generated
   */
  EReference getRange_Bound_lower();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Range#getBound_upp <em>Bound upp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bound upp</em>'.
   * @see org.xtext.example.mydsl.adeptness.Range#getBound_upp()
   * @see #getRange()
   * @generated
   */
  EReference getRange_Bound_upp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Gap <em>Gap</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gap</em>'.
   * @see org.xtext.example.mydsl.adeptness.Gap
   * @generated
   */
  EClass getGap();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Gap#getBound_lower <em>Bound lower</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bound lower</em>'.
   * @see org.xtext.example.mydsl.adeptness.Gap#getBound_lower()
   * @see #getGap()
   * @generated
   */
  EReference getGap_Bound_lower();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Gap#getBound_upp <em>Bound upp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bound upp</em>'.
   * @see org.xtext.example.mydsl.adeptness.Gap#getBound_upp()
   * @see #getGap()
   * @generated
   */
  EReference getGap_Bound_upp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.InclusiveBound <em>Inclusive Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inclusive Bound</em>'.
   * @see org.xtext.example.mydsl.adeptness.InclusiveBound
   * @generated
   */
  EClass getInclusiveBound();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.adeptness.InclusiveBound#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.adeptness.InclusiveBound#getName()
   * @see #getInclusiveBound()
   * @generated
   */
  EAttribute getInclusiveBound_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.InclusiveBound#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.adeptness.InclusiveBound#getValue()
   * @see #getInclusiveBound()
   * @generated
   */
  EReference getInclusiveBound_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Bound_up <em>Bound up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bound up</em>'.
   * @see org.xtext.example.mydsl.adeptness.Bound_up
   * @generated
   */
  EClass getBound_up();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Bound_up#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.adeptness.Bound_up#getValue()
   * @see #getBound_up()
   * @generated
   */
  EReference getBound_up_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.Bound_Down <em>Bound Down</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bound Down</em>'.
   * @see org.xtext.example.mydsl.adeptness.Bound_Down
   * @generated
   */
  EClass getBound_Down();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.adeptness.Bound_Down#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.adeptness.Bound_Down#getValue()
   * @see #getBound_Down()
   * @generated
   */
  EReference getBound_Down_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.BOOLEAN <em>BOOLEAN</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BOOLEAN</em>'.
   * @see org.xtext.example.mydsl.adeptness.BOOLEAN
   * @generated
   */
  EClass getBOOLEAN();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.adeptness.BOOLEAN#isBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see org.xtext.example.mydsl.adeptness.BOOLEAN#isBool()
   * @see #getBOOLEAN()
   * @generated
   */
  EAttribute getBOOLEAN_Bool();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.DOUBLE <em>DOUBLE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DOUBLE</em>'.
   * @see org.xtext.example.mydsl.adeptness.DOUBLE
   * @generated
   */
  EClass getDOUBLE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.adeptness.DOUBLE#getDVal <em>DVal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>DVal</em>'.
   * @see org.xtext.example.mydsl.adeptness.DOUBLE#getDVal()
   * @see #getDOUBLE()
   * @generated
   */
  EAttribute getDOUBLE_DVal();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see org.xtext.example.mydsl.adeptness.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.adeptness.PackageDeclaration <em>Package Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Declaration</em>'.
   * @see org.xtext.example.mydsl.adeptness.PackageDeclaration
   * @generated
   */
  EClass getPackageDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.adeptness.PackageDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.adeptness.PackageDeclaration#getName()
   * @see #getPackageDeclaration()
   * @generated
   */
  EAttribute getPackageDeclaration_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.adeptness.PackageDeclaration#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.adeptness.PackageDeclaration#getElements()
   * @see #getPackageDeclaration()
   * @generated
   */
  EReference getPackageDeclaration_Elements();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AdeptnessFactory getAdeptnessFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.AdeptnessImpl <em>Adeptness</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getAdeptness()
     * @generated
     */
    EClass ADEPTNESS = eINSTANCE.getAdeptness();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADEPTNESS__ELEMENTS = eINSTANCE.getAdeptness_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.AbstractElementImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.ImportImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.TypeImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.SignalImpl <em>Signal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.SignalImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getSignal()
     * @generated
     */
    EClass SIGNAL = eINSTANCE.getSignal();

    /**
     * The meta object literal for the '<em><b>Oracle</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIGNAL__ORACLE = eINSTANCE.getSignal_Oracle();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.OracleImpl <em>Oracle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.OracleImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getOracle()
     * @generated
     */
    EClass ORACLE = eINSTANCE.getOracle();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORACLE__NAME = eINSTANCE.getOracle_Name();

    /**
     * The meta object literal for the '<em><b>Check</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORACLE__CHECK = eINSTANCE.getOracle_Check();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.CheckImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK__NAME = eINSTANCE.getCheck_Name();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__REFERENCE = eINSTANCE.getCheck_Reference();

    /**
     * The meta object literal for the '<em><b>Fail Reason</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__FAIL_REASON = eINSTANCE.getCheck_FailReason();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK__DESCRIPTION = eINSTANCE.getCheck_Description();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.FailReasonImpl <em>Fail Reason</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.FailReasonImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getFailReason()
     * @generated
     */
    EClass FAIL_REASON = eINSTANCE.getFailReason();

    /**
     * The meta object literal for the '<em><b>High Peak</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAIL_REASON__HIGH_PEAK = eINSTANCE.getFailReason_HighPeak();

    /**
     * The meta object literal for the '<em><b>High Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAIL_REASON__HIGH_TIME = eINSTANCE.getFailReason_HighTime();

    /**
     * The meta object literal for the '<em><b>Const Deg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAIL_REASON__CONST_DEG = eINSTANCE.getFailReason_ConstDeg();

    /**
     * The meta object literal for the '<em><b>XPeaks</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAIL_REASON__XPEAKS = eINSTANCE.getFailReason_XPeaks();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.XPeaksImpl <em>XPeaks</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.XPeaksImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getXPeaks()
     * @generated
     */
    EClass XPEAKS = eINSTANCE.getXPeaks();

    /**
     * The meta object literal for the '<em><b>Cant</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XPEAKS__CANT = eINSTANCE.getXPeaks_Cant();

    /**
     * The meta object literal for the '<em><b>NPeaks</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XPEAKS__NPEAKS = eINSTANCE.getXPeaks_NPeaks();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XPEAKS__TIME = eINSTANCE.getXPeaks_Time();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.ConstDegImpl <em>Const Deg</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.ConstDegImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getConstDeg()
     * @generated
     */
    EClass CONST_DEG = eINSTANCE.getConstDeg();

    /**
     * The meta object literal for the '<em><b>Cant</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONST_DEG__CANT = eINSTANCE.getConstDeg_Cant();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.HighTimeImpl <em>High Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.HighTimeImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getHighTime()
     * @generated
     */
    EClass HIGH_TIME = eINSTANCE.getHighTime();

    /**
     * The meta object literal for the '<em><b>Cant</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HIGH_TIME__CANT = eINSTANCE.getHighTime_Cant();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HIGH_TIME__TIME = eINSTANCE.getHighTime_Time();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.HighPeakImpl <em>High Peak</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.HighPeakImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getHighPeak()
     * @generated
     */
    EClass HIGH_PEAK = eINSTANCE.getHighPeak();

    /**
     * The meta object literal for the '<em><b>Cant</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HIGH_PEAK__CANT = eINSTANCE.getHighPeak_Cant();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.ReferenceImpl <em>Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.ReferenceImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getReference()
     * @generated
     */
    EClass REFERENCE = eINSTANCE.getReference();

    /**
     * The meta object literal for the '<em><b>Upper</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__UPPER = eINSTANCE.getReference_Upper();

    /**
     * The meta object literal for the '<em><b>Lower</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__LOWER = eINSTANCE.getReference_Lower();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__RANGE = eINSTANCE.getReference_Range();

    /**
     * The meta object literal for the '<em><b>Gap</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__GAP = eINSTANCE.getReference_Gap();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.UpperImpl <em>Upper</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.UpperImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getUpper()
     * @generated
     */
    EClass UPPER = eINSTANCE.getUpper();

    /**
     * The meta object literal for the '<em><b>Bound upp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UPPER__BOUND_UPP = eINSTANCE.getUpper_Bound_upp();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.LowerImpl <em>Lower</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.LowerImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getLower()
     * @generated
     */
    EClass LOWER = eINSTANCE.getLower();

    /**
     * The meta object literal for the '<em><b>Bound lower</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOWER__BOUND_LOWER = eINSTANCE.getLower_Bound_lower();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.RangeImpl <em>Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.RangeImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getRange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getRange();

    /**
     * The meta object literal for the '<em><b>Bound lower</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RANGE__BOUND_LOWER = eINSTANCE.getRange_Bound_lower();

    /**
     * The meta object literal for the '<em><b>Bound upp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RANGE__BOUND_UPP = eINSTANCE.getRange_Bound_upp();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.GapImpl <em>Gap</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.GapImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getGap()
     * @generated
     */
    EClass GAP = eINSTANCE.getGap();

    /**
     * The meta object literal for the '<em><b>Bound lower</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAP__BOUND_LOWER = eINSTANCE.getGap_Bound_lower();

    /**
     * The meta object literal for the '<em><b>Bound upp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAP__BOUND_UPP = eINSTANCE.getGap_Bound_upp();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.InclusiveBoundImpl <em>Inclusive Bound</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.InclusiveBoundImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getInclusiveBound()
     * @generated
     */
    EClass INCLUSIVE_BOUND = eINSTANCE.getInclusiveBound();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INCLUSIVE_BOUND__NAME = eINSTANCE.getInclusiveBound_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INCLUSIVE_BOUND__VALUE = eINSTANCE.getInclusiveBound_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.Bound_upImpl <em>Bound up</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.Bound_upImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getBound_up()
     * @generated
     */
    EClass BOUND_UP = eINSTANCE.getBound_up();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOUND_UP__VALUE = eINSTANCE.getBound_up_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.Bound_DownImpl <em>Bound Down</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.Bound_DownImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getBound_Down()
     * @generated
     */
    EClass BOUND_DOWN = eINSTANCE.getBound_Down();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOUND_DOWN__VALUE = eINSTANCE.getBound_Down_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.BOOLEANImpl <em>BOOLEAN</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.BOOLEANImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getBOOLEAN()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBOOLEAN();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__BOOL = eINSTANCE.getBOOLEAN_Bool();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.DOUBLEImpl <em>DOUBLE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.DOUBLEImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getDOUBLE()
     * @generated
     */
    EClass DOUBLE = eINSTANCE.getDOUBLE();

    /**
     * The meta object literal for the '<em><b>DVal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOUBLE__DVAL = eINSTANCE.getDOUBLE_DVal();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.DataTypeImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.adeptness.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.adeptness.impl.PackageDeclarationImpl
     * @see org.xtext.example.mydsl.adeptness.impl.AdeptnessPackageImpl#getPackageDeclaration()
     * @generated
     */
    EClass PACKAGE_DECLARATION = eINSTANCE.getPackageDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE_DECLARATION__NAME = eINSTANCE.getPackageDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE_DECLARATION__ELEMENTS = eINSTANCE.getPackageDeclaration_Elements();

  }

} //AdeptnessPackage
