/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.adeptness;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Eval Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.adeptness.AdeptnessPackage#getEvalExpression()
 * @model
 * @generated
 */
public interface EvalExpression extends AbstractElement2
{
} // EvalExpression
