/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.adeptness;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fail Reason</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.adeptness.FailReason#getReason <em>Reason</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.adeptness.AdeptnessPackage#getFailReason()
 * @model
 * @generated
 */
public interface FailReason extends EObject
{
  /**
   * Returns the value of the '<em><b>Reason</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reason</em>' containment reference.
   * @see #setReason(Reason)
   * @see org.xtext.example.mydsl.adeptness.AdeptnessPackage#getFailReason_Reason()
   * @model containment="true"
   * @generated
   */
  Reason getReason();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.adeptness.FailReason#getReason <em>Reason</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reason</em>' containment reference.
   * @see #getReason()
   * @generated
   */
  void setReason(Reason value);

} // FailReason
