/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.adeptness.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.adeptness.AdeptnessPackage;
import org.xtext.example.mydsl.adeptness.EvalExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Eval Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EvalExpressionImpl extends AbstractElement2Impl implements EvalExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EvalExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AdeptnessPackage.Literals.EVAL_EXPRESSION;
  }

} //EvalExpressionImpl
