/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.adeptness.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.adeptness.AdeptnessPackage;
import org.xtext.example.mydsl.adeptness.MonitoringFile;
import org.xtext.example.mydsl.adeptness.MonitoringPlan;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Monitoring File</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.adeptness.impl.MonitoringFileImpl#getMonitoringPlan <em>Monitoring Plan</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MonitoringFileImpl extends TypeImpl implements MonitoringFile
{
  /**
   * The cached value of the '{@link #getMonitoringPlan() <em>Monitoring Plan</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMonitoringPlan()
   * @generated
   * @ordered
   */
  protected EList<MonitoringPlan> monitoringPlan;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MonitoringFileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AdeptnessPackage.Literals.MONITORING_FILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MonitoringPlan> getMonitoringPlan()
  {
    if (monitoringPlan == null)
    {
      monitoringPlan = new EObjectContainmentEList<MonitoringPlan>(MonitoringPlan.class, this, AdeptnessPackage.MONITORING_FILE__MONITORING_PLAN);
    }
    return monitoringPlan;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AdeptnessPackage.MONITORING_FILE__MONITORING_PLAN:
        return ((InternalEList<?>)getMonitoringPlan()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AdeptnessPackage.MONITORING_FILE__MONITORING_PLAN:
        return getMonitoringPlan();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AdeptnessPackage.MONITORING_FILE__MONITORING_PLAN:
        getMonitoringPlan().clear();
        getMonitoringPlan().addAll((Collection<? extends MonitoringPlan>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AdeptnessPackage.MONITORING_FILE__MONITORING_PLAN:
        getMonitoringPlan().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AdeptnessPackage.MONITORING_FILE__MONITORING_PLAN:
        return monitoringPlan != null && !monitoringPlan.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //MonitoringFileImpl
