/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.adeptness.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.adeptness.AdeptnessPackage;
import org.xtext.example.mydsl.adeptness.At_least;
import org.xtext.example.mydsl.adeptness.At_most;
import org.xtext.example.mydsl.adeptness.Bound_Down;
import org.xtext.example.mydsl.adeptness.Bound_up;
import org.xtext.example.mydsl.adeptness.Exactly;
import org.xtext.example.mydsl.adeptness.Range;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Range</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.adeptness.impl.RangeImpl#getBound_lower <em>Bound lower</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.adeptness.impl.RangeImpl#getBound_upp <em>Bound upp</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.adeptness.impl.RangeImpl#getExactly <em>Exactly</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.adeptness.impl.RangeImpl#getAtmost <em>Atmost</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.adeptness.impl.RangeImpl#getAtleast <em>Atleast</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RangeImpl extends MinimalEObjectImpl.Container implements Range
{
  /**
   * The cached value of the '{@link #getBound_lower() <em>Bound lower</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBound_lower()
   * @generated
   * @ordered
   */
  protected Bound_Down bound_lower;

  /**
   * The cached value of the '{@link #getBound_upp() <em>Bound upp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBound_upp()
   * @generated
   * @ordered
   */
  protected Bound_up bound_upp;

  /**
   * The cached value of the '{@link #getExactly() <em>Exactly</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExactly()
   * @generated
   * @ordered
   */
  protected Exactly exactly;

  /**
   * The cached value of the '{@link #getAtmost() <em>Atmost</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtmost()
   * @generated
   * @ordered
   */
  protected At_most atmost;

  /**
   * The cached value of the '{@link #getAtleast() <em>Atleast</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtleast()
   * @generated
   * @ordered
   */
  protected At_least atleast;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AdeptnessPackage.Literals.RANGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Bound_Down getBound_lower()
  {
    return bound_lower;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBound_lower(Bound_Down newBound_lower, NotificationChain msgs)
  {
    Bound_Down oldBound_lower = bound_lower;
    bound_lower = newBound_lower;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__BOUND_LOWER, oldBound_lower, newBound_lower);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBound_lower(Bound_Down newBound_lower)
  {
    if (newBound_lower != bound_lower)
    {
      NotificationChain msgs = null;
      if (bound_lower != null)
        msgs = ((InternalEObject)bound_lower).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__BOUND_LOWER, null, msgs);
      if (newBound_lower != null)
        msgs = ((InternalEObject)newBound_lower).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__BOUND_LOWER, null, msgs);
      msgs = basicSetBound_lower(newBound_lower, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__BOUND_LOWER, newBound_lower, newBound_lower));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Bound_up getBound_upp()
  {
    return bound_upp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBound_upp(Bound_up newBound_upp, NotificationChain msgs)
  {
    Bound_up oldBound_upp = bound_upp;
    bound_upp = newBound_upp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__BOUND_UPP, oldBound_upp, newBound_upp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBound_upp(Bound_up newBound_upp)
  {
    if (newBound_upp != bound_upp)
    {
      NotificationChain msgs = null;
      if (bound_upp != null)
        msgs = ((InternalEObject)bound_upp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__BOUND_UPP, null, msgs);
      if (newBound_upp != null)
        msgs = ((InternalEObject)newBound_upp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__BOUND_UPP, null, msgs);
      msgs = basicSetBound_upp(newBound_upp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__BOUND_UPP, newBound_upp, newBound_upp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Exactly getExactly()
  {
    return exactly;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExactly(Exactly newExactly, NotificationChain msgs)
  {
    Exactly oldExactly = exactly;
    exactly = newExactly;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__EXACTLY, oldExactly, newExactly);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExactly(Exactly newExactly)
  {
    if (newExactly != exactly)
    {
      NotificationChain msgs = null;
      if (exactly != null)
        msgs = ((InternalEObject)exactly).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__EXACTLY, null, msgs);
      if (newExactly != null)
        msgs = ((InternalEObject)newExactly).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__EXACTLY, null, msgs);
      msgs = basicSetExactly(newExactly, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__EXACTLY, newExactly, newExactly));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public At_most getAtmost()
  {
    return atmost;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtmost(At_most newAtmost, NotificationChain msgs)
  {
    At_most oldAtmost = atmost;
    atmost = newAtmost;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__ATMOST, oldAtmost, newAtmost);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAtmost(At_most newAtmost)
  {
    if (newAtmost != atmost)
    {
      NotificationChain msgs = null;
      if (atmost != null)
        msgs = ((InternalEObject)atmost).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__ATMOST, null, msgs);
      if (newAtmost != null)
        msgs = ((InternalEObject)newAtmost).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__ATMOST, null, msgs);
      msgs = basicSetAtmost(newAtmost, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__ATMOST, newAtmost, newAtmost));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public At_least getAtleast()
  {
    return atleast;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtleast(At_least newAtleast, NotificationChain msgs)
  {
    At_least oldAtleast = atleast;
    atleast = newAtleast;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__ATLEAST, oldAtleast, newAtleast);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAtleast(At_least newAtleast)
  {
    if (newAtleast != atleast)
    {
      NotificationChain msgs = null;
      if (atleast != null)
        msgs = ((InternalEObject)atleast).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__ATLEAST, null, msgs);
      if (newAtleast != null)
        msgs = ((InternalEObject)newAtleast).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AdeptnessPackage.RANGE__ATLEAST, null, msgs);
      msgs = basicSetAtleast(newAtleast, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AdeptnessPackage.RANGE__ATLEAST, newAtleast, newAtleast));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AdeptnessPackage.RANGE__BOUND_LOWER:
        return basicSetBound_lower(null, msgs);
      case AdeptnessPackage.RANGE__BOUND_UPP:
        return basicSetBound_upp(null, msgs);
      case AdeptnessPackage.RANGE__EXACTLY:
        return basicSetExactly(null, msgs);
      case AdeptnessPackage.RANGE__ATMOST:
        return basicSetAtmost(null, msgs);
      case AdeptnessPackage.RANGE__ATLEAST:
        return basicSetAtleast(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AdeptnessPackage.RANGE__BOUND_LOWER:
        return getBound_lower();
      case AdeptnessPackage.RANGE__BOUND_UPP:
        return getBound_upp();
      case AdeptnessPackage.RANGE__EXACTLY:
        return getExactly();
      case AdeptnessPackage.RANGE__ATMOST:
        return getAtmost();
      case AdeptnessPackage.RANGE__ATLEAST:
        return getAtleast();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AdeptnessPackage.RANGE__BOUND_LOWER:
        setBound_lower((Bound_Down)newValue);
        return;
      case AdeptnessPackage.RANGE__BOUND_UPP:
        setBound_upp((Bound_up)newValue);
        return;
      case AdeptnessPackage.RANGE__EXACTLY:
        setExactly((Exactly)newValue);
        return;
      case AdeptnessPackage.RANGE__ATMOST:
        setAtmost((At_most)newValue);
        return;
      case AdeptnessPackage.RANGE__ATLEAST:
        setAtleast((At_least)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AdeptnessPackage.RANGE__BOUND_LOWER:
        setBound_lower((Bound_Down)null);
        return;
      case AdeptnessPackage.RANGE__BOUND_UPP:
        setBound_upp((Bound_up)null);
        return;
      case AdeptnessPackage.RANGE__EXACTLY:
        setExactly((Exactly)null);
        return;
      case AdeptnessPackage.RANGE__ATMOST:
        setAtmost((At_most)null);
        return;
      case AdeptnessPackage.RANGE__ATLEAST:
        setAtleast((At_least)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AdeptnessPackage.RANGE__BOUND_LOWER:
        return bound_lower != null;
      case AdeptnessPackage.RANGE__BOUND_UPP:
        return bound_upp != null;
      case AdeptnessPackage.RANGE__EXACTLY:
        return exactly != null;
      case AdeptnessPackage.RANGE__ATMOST:
        return atmost != null;
      case AdeptnessPackage.RANGE__ATLEAST:
        return atleast != null;
    }
    return super.eIsSet(featureID);
  }

} //RangeImpl
