/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.example.mydsl.tests.AdeptnessInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(AdeptnessInjectorProvider.class)
@SuppressWarnings("all")
public class AdeptnessParsingTest {
  @Inject
  @Test
  public void loadModel() {
  }
}
